### ISSUE TITLE
搜狗翻译似乎失效了

### ISSUE THREAD

**Issue by miaomiaosoft** [Firefox-Pro-Coding/iciba-translate-userscript#11]
可能是调用的JS和KEY变更了，现在的是“fb3eeb5c203d77031d19ad06a6a0da30”
https://dlweb.sogoucdn.com/translate/pc/static/js/app.12ec0d5d.js
KEY在上面这段JS内，但这个JS文件名中的“12ec0d5d”是会经常更换的，所以导致一段时间就失效
我个人的做法，从网页源码中取最新的JS文件地址，再正则取JS文件内的KEY

**Comment by noe132** [comment]
`v4.2.4` 已自动获取key. 👌
