### ISSUE TITLE
能否设置翻译黑名单

### ISSUE THREAD

**Issue by chaofengxn** [Firefox-Pro-Coding/iciba-translate-userscript#14]
大部分我浏览的网站不需要翻译，在这些网站上不需要执行脚本，会影响网页加载速度。因此可以支持添加黑名单吗？

**Comment by noe132** [comment]
无法支持。想要黑名单，只能从脚本管理器上修改设置，而无法在脚本中加黑名单。因为就算脚本什么都不做，浏览器也是要解析脚本内容的。

实际上开启脚本目前消耗的资源并不多。经过测试，从profile结果来看，开启脚本在每个标签页需要大约10M的内存，大约使用了100ms不到的cpu时间。
从结果来看影响并不大，除非开同时几十上百个标签页。

而且目前在第一次点击小圆圈之前主要的功能并不会加载，部分消耗资源的操作是延迟执行的。
