### ISSUE TITLE
能不能增加bing翻译的接口啊？

### ISSUE THREAD

**Issue by haoisli9** [Firefox-Pro-Coding/iciba-translate-userscript#15]
bing字典翻译挺不错，能不能增加这个接口呢？多谢啦；
非常好的插件；

**Comment by noe132** [comment]
可以的。不过需要一些时间。

**Comment by haoisli9** [comment]
多谢啦

**Comment by noe132** [comment]
已在 `v4.4.0` 添加bing翻译接口。需要在设置里手动启用。

**Comment by noe132** [comment]
你说的是不是 https://cn.bing.com/dict/ 这个必应词典?.....
我似乎理解成bing翻译了

**Comment by aijzdi** [comment]
想做英语方面的，这个脚本可以部署到我自己的网站嘛？

**Comment by aijzdi** [comment]
然后划词翻译

**Comment by noe132** [comment]
@ryan-dream 
> 想做英语方面的，这个脚本可以部署到我自己的网站嘛？

可以，如果你知道怎么弄。我这边暂时不会提供技术支持，因为目前没有时间。
当然，如果能把源地址附上是最好，不过你也可以不附上，项目是MIT协议的。
