### ISSUE TITLE
请求添加功能（你的插件真牛逼）

### ISSUE THREAD

**Issue by miderxi** [Firefox-Pro-Coding/iciba-translate-userscript#16]
不支持本地用浏览器打开的pdf文件的划词翻译

**Comment by noe132** [comment]
浏览器打开的pdf，扩展管理器不会注入脚本，所以无法在里面查词。

**Comment by miderxi** [comment]
原来这样，好吧


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: noe132 <notifications@github.com>
发送时间: 2019年7月14日 10:59
收件人: Firefox-Pro-Coding/iciba-translate-userscript <iciba-translate-userscript@noreply.github.com>
抄送: miderxi <1965770446@qq.com>, Author <author@noreply.github.com>
主题: 回复：[Firefox-Pro-Coding/iciba-translate-userscript] 请求添加功能（你的插件真牛逼） (#16)




浏览器打开的pdf，扩展管理器不会注入脚本，所以无法在里面查词。
