### ISSUE TITLE
firefox54+Tampermonkey 4.9.5921失效

### ISSUE THREAD

**Issue by tooyangtoonaive** [Firefox-Pro-Coding/iciba-translate-userscript#17]
**问题描述**
选中文字不能显示圆形图标

**重现步骤**
请简要描述问题重现的步骤，如：
1. 选中文字不能显示圆形图标

**预期表现**
显示圆形图标

**截图**

**环境**
 - 用户脚本版本:  4.0.0
 - 系统: win7 sp1
 - 浏览器及版本 firefox 54.0.1
 - 脚本管理扩展 Tampermonkey 4.9.5921

**附加说明**
其他的附加说明添加到这里。

**Comment by noe132** [comment]
正在修复

**Comment by noe132** [comment]
fixed in `v4.4.1`
