### ISSUE TITLE
搜狗翻译失效，token方式换了

### ISSUE THREAD

**Issue by miaomiaosoft** [Firefox-Pro-Coding/iciba-translate-userscript#18]
get访问
https://fanyi.sogou.com/logtrace
然后拼接两个引号的部分

**Comment by noe132** [comment]
fixed in `v4.4.1`

**Comment by loveqianool** [comment]
![sogou](https://cdn.jsdelivr.net/gh/sbough1/z/images/2019/10/15/6f253c3a810640dc2fcca83fcf4d9be9.png)

我这边已经两个多月无法使用了，我尝试了安装一个全新的 Firefox 使用 暴力猴 安装最新的 4.4.2 版本，依然是这个错误。

**Comment by miaomiaosoft** [comment]
方式又换了，搜狗换的太频繁我就不好意思向作者再反馈了
这次好像要提交cookies才会返回正确的token

**Comment by weaming** [comment]
参考 https://github.com/weaming/sogou/blob/master/sogou.py#L92 可以获取 seccode

**Comment by noe132** [comment]
v4.4.3已修复。已曲线救国获取token👀
