### ISSUE TITLE
在某些页面不起作用

### ISSUE THREAD

**Issue by jyuan15** [Firefox-Pro-Coding/iciba-translate-userscript#21]
**问题描述**
比如在火狐扩展的评论页和Chrome扩展的评论页都不起效，而且Tampermonkey在这两个页面都显示“没有运行的脚本”。

**重现步骤**
请简要描述问题重现的步骤，如：
1. 点击 '...'
2. 打开 '....'
3. 滚动到 '....'
4. 出现问题

**预期表现**
请简要描述被期望的表现。

**截图**
![图片](https://user-images.githubusercontent.com/12642186/73058134-f5b94900-3ecd-11ea-9663-3dfff1588d20.png)
![图片](https://user-images.githubusercontent.com/12642186/73058534-cce58380-3ece-11ea-826c-7fe8a3d07163.png)

**环境**
 - 用户脚本版本: 4.4.3
 - 系统: Windows 7
 - 浏览器及版本 chrome 79，firefox 68
 - 脚本管理扩展 tampermonkey

**附加说明**
其他的附加说明添加到这里。

**Comment by noe132** [comment]
所有的浏览器内建页面，其他扩展的页面，以及包括浏览器应用商店页面，被浏览器认为是不允许外部程序修改的页面。所有扩展在此类页面都将没有效果。
