### ISSUE TITLE
搜狗失效

### ISSUE THREAD

**Issue by miaomiaosoft** [Firefox-Pro-Coding/iciba-translate-userscript#22]
- 搜狗翻译好像又失效了
- 现在是默认会按标点符号来给翻译文本重新换行，感觉还是按原文的换行比较好，或者可以的话提供一个开关

谢谢

**Comment by noe132** [comment]
新版本已经解决了搜狗翻译的问题，预计4.5.1时会上传到greasyfork。
不过 因为 greasyfork#648 的原因，greasyfork上传暂时挂了，估计得等这个issue解决了

你可以手动更改解决一下搜狗翻译的问题，在代码里搜索 `window.location.origin` 会找到一处位置，将接下来的三处`window`换成`unsafeWindow`理论上就可以了
```
window.location.origin&&window.addEventListener("load",function(){var t=window.seccode;
替换为
unsafeWindow.location.origin&&unsafeWindow.addEventListener("load",function(){var t=unsafeWindow.seccode;
```
<br>
  
> 现在是默认会按标点符号来给翻译文本重新换行

这个能给个简单的例子么，我搜狗翻译基本没怎么用，你举个例子说明你期望的表现就行

**Comment by miaomiaosoft** [comment]
OK,谢谢

“现在是默认会按标点符号来给翻译文本重新换行”
上面没说清楚，搜狗不能用所以一直用的谷歌，目前看来只有谷歌翻译会这样，看图
![QQ截图20200204221851](https://user-images.githubusercontent.com/4084875/73752844-9e07c100-479c-11ea-94c6-33d29bef2127.jpg)
红框处应该是一整行，但翻译结果却分为多行

必应好像也不能用了

**Comment by noe132** [comment]
搜狗翻译和谷歌翻译换行已在 `v4.5.2` 修复
