### ISSUE TITLE
鼠标 hover 查词不再自动翻译选中的单词

### ISSUE THREAD

**Issue by erhandsome** [Firefox-Pro-Coding/iciba-translate-userscript#23]
4.6.0版本设置中开启 鼠标hover查词后，选中单词移动到小圆圈，不会自动调用默认翻译接口翻译了，需要点击对应图标才翻译，之前是可以直接翻译的，前几天开始出现

出现问题的环境：
 - 页面链接 所有页面
 - 浏览器版本 firefox 73.0
 - 脚本管理扩展 tampermonkey

**Comment by noe132** [comment]
`v4.6.1` 已修复 hover 查词未自动翻译的问题
