### ISSUE TITLE
默认接口设置无效

### ISSUE THREAD

**Issue by miaomiaosoft** [Firefox-Pro-Coding/iciba-translate-userscript#24]
默认接口 谷歌
备用接口 百度
但划词后使用的却是第一个也就是ICIBA翻译

另外，这个蓝框感觉多余了，前几个版本应该是没有的，可否考虑去掉
![QQ截图20200223181558](https://user-images.githubusercontent.com/4084875/75110391-ae5adf80-5668-11ea-8e37-990c37d83312.jpg)

**Comment by noe132** [comment]
已确认bug。
蓝框是focus的效果。下个patch会加个选项是否点击后自动focus输入框，默认为false

**Comment by noe132** [comment]
已在 `v4.6.2` 修复了这个默认接口不对的问题。你确认一下。

自动 focus 新增了一个选项。
