### ISSUE TITLE
在推特上并不工作

### ISSUE THREAD

**Issue by abolast** [Firefox-Pro-Coding/iciba-translate-userscript#26]
环境：Ubuntu18.04  Firefox75  Tampermonkey  iciba划词翻译4.7.3

在其他网页上都能正常工作，在推特上选中英文并不弹出圆圈，另一个插件Simple Translate是可以正常弹出来的

**Comment by noe132** [comment]
这是 tampermonkey 上的一个 issue
https://github.com/Tampermonkey/tampermonkey/issues/700

会导致所有设置了script-src CSP 规则的页面无法执行任何脚本。

除了等 tampermonkey 解决这个问题之外
1. 设置 about:config `security.csp.enable` 为 false。不过这将禁用整个浏览器的CSP。虽然禁用CSP一半来说不会带来安全问题，但这不算是一个比较好的解决方案
2. 使用 [greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)。greasemonkey 似乎没有这个问题。

**Comment by abolast** [comment]
设置 about:config security.csp.enable 为 false 之后还是无法在推特上使用，所以还是等待tampermonkey 解决问题吧。庆幸的是推特自带了翻译推文的功能。
