### ISSUE TITLE
使用iciba引擎时,点击发音图标并不能发音而是直接下载了一个相应的MP3文件

### ISSUE THREAD

**Issue by feadsf** [Firefox-Pro-Coding/iciba-translate-userscript#29]
使用iciba引擎时,点击发音图标并不能发音而是直接下载了一个相应的MP3文件
 - 页面链接: 任意一个网页
 - 浏览器版本:firefox 77.0.1(64位)
 - 脚本管理扩展:Tampermonkey  4.11.6114

**Comment by noe132** [comment]
未能在firefox上重现。能提供截图或者录屏吗？

**Comment by noe132** [comment]
这是我在firefox 77 tampermonkey 4.11 下测试的录屏，能够正常播放音频，浏览器tab也有喇叭图标
![](https://user-images.githubusercontent.com/2271900/84580995-24997280-ae0f-11ea-8fdb-339baa76eb97.gif)

**Comment by feadsf** [comment]
我的录屏
[bandicam 2020-06-14 21-10-23-151.zip](https://github.com/Firefox-Pro-Coding/iciba-translate-userscript/files/4776437/bandicam.2020-06-14.21-10-23-151.zip)

**Comment by noe132** [comment]
建议将播放的MP3文件url添加到IDM排除名单。脚本这边不能阻止idm监听下载请求。
