### ISSUE TITLE
报错，显示“ICIBA: GM is not defined”

### ISSUE THREAD

**Issue by devxia** [Firefox-Pro-Coding/iciba-translate-userscript#3]
**问题描述**
翻译报错，显示“ICIBA: GM is not defined”

**重现**
划词后按住白色按钮，翻译任意单词、段落均会出现

**截图**
![2019-04-14_18-58-28](https://user-images.githubusercontent.com/8263704/56091919-b47c1d80-5ee7-11e9-9a3b-2d789f84504c.png)

**环境**
 - 系统: Windows 10
 - 浏览器 chrome 73.0.3683.103

**Comment by noe132** [comment]
fixed in https://github.com/Firefox-Pro-Coding/iciba-translate-userscript/commit/2eefa66b2a6fff439baa81805619bcedbee88168
在 4.0.5 已修复。
