### ISSUE TITLE
关于新增一键复制功能的建议

### ISSUE THREAD

**Issue by abc1044** [Firefox-Pro-Coding/iciba-translate-userscript#36]
是否可以考虑新增一键复制按钮，像翻译软件一样。可以在窗口的角落里放一个复制按钮，方便快速复制大段文字的翻译。

示意图：
![image](https://user-images.githubusercontent.com/18114052/86884068-97072500-c125-11ea-8c36-2eb1af6bef4e.png)
![image](https://user-images.githubusercontent.com/18114052/86884123-af773f80-c125-11ea-8b7f-0cb5419ab8c0.png)

**Comment by noe132** [comment]
你给出的截图，是从iciba获取的数据，结果和 https://www.iciba.com/word?w=This%20is%20a%20test%20text 是一样的。
iciba接口的主要功能是查询单词的解释，翻译只是简单提供的功能

如果加上复制按钮，我认为google翻译，baidu翻译，搜狗翻译也应该需要加上复制按钮，否则用户体验不一致。
而其他翻译接口的结果，在左下角相应位置已经有朗读功能的按钮存在了，会和已有功能产生一些冲突

我觉得一键复制翻译文本并不算一个很高频的需求，如果需要复制，手动选择翻译复制并没有增加太多的操作步骤。

**Comment by abc1044** [comment]
可能会带来的现有功能冲突确实是一个问题，认同非高频需求的观点，保持功能简洁和好用确实很重要。这是我一点点小建议，提出来看看。不方便添加的话，那我先把issue关了。
