### ISSUE TITLE
发现改版了,作为忠实用户特来反馈一帖bug

### ISSUE THREAD

**Issue by MedusaSTears** [Firefox-Pro-Coding/iciba-translate-userscript#4]
**问题描述**
谷歌词典刚开始一直不好使,不知道从什么时候开始变好的

**截图**
![Avw8eg.png](https://s2.ax1x.com/2019/04/16/Avw8eg.png)

**环境**
 - 用户脚本版本:4.0.4
 - 系统: Windows 10
 - 浏览器及版本 Cent Browser版本 3.9.2.45（正式版本） （32 位） (portable) (Chromium 72.0.3626.121)
 - 脚本管理扩展 tampermonkey

**附加说明**
感谢作者一直以来的付出,我一直在用这个脚本,已经无法自拨(bo)的爱上他了
不知可否和这个软件互相借鉴,变成windows环境而不仅仅是浏览器
https://github.com/CopyTranslator/CopyTranslator

另外附上我觉得奇葩的翻译:
这两个都是词霸接口的:
![Av6Vj1.png](https://s2.ax1x.com/2019/04/16/Av6Vj1.png)
![Av6mB6.png](https://s2.ax1x.com/2019/04/16/Av6mB6.png)
这个是谷歌词典的:
![Av6enx.png](https://s2.ax1x.com/2019/04/16/Av6enx.png)

**Comment by MedusaSTears** [comment]
![Av2eun.png](https://s2.ax1x.com/2019/04/16/Av2eun.png)

**Comment by noe132** [comment]
不打算做系统上的支持，因为需要打包electron，而且显示查词框很不好实现。

Google字典目前只能查词，遇到查不到的词就报错了。之后计划是修改成查不到的词自动使用google翻译。

剪贴板查词我有个想法，就是右键点击小圆圈使用剪贴板而不是选择文字查词，这样稍微方便一些，你看这个怎么样

**Comment by noe132** [comment]
剪贴板查词目前来看实现不了。浏览器提供的获取剪贴板API需要用户授权，并且是每个域名需要授权一次。就是说在不同的网页使用剪贴板会要多次授权。目前油猴tampermonkey都没有获取剪贴板相关的api。

**Comment by noe132** [comment]
固定拖动的功能在 v4.0.6 实现了。
google字典 backend error 是因为查不到词。request failed 0 是因为多次查不到词，api返回的是500，而chrome认为500太多可能会存在ddos，自动拦截请求了。
剪切板无法在用户脚本内实现，因为API限制。除非使用扩展
