### ISSUE TITLE
希望增加翻译的历史记录或者前一个翻译结果按钮

### ISSUE THREAD

**Issue by ghost** [Firefox-Pro-Coding/iciba-translate-userscript#40]
这样子的话可以更方便达到纯英文环境学习单词的效果。

历史记录有10个就可以了，或者再少些也没关系。
前一个翻译结果按钮就是点击后跳转到前一次查询翻译的翻译结果页面，当然这个要是能前进后退是更好，不过如果只能一个也能改善很多了。
这两个功能的目的都是方便学习英文，我觉得翻译软件能让使用者减少使用其的频率也是非常好的。

我的使用方法是设置默认词典是英文，英文的翻译结果里有不懂的单词直接又查询翻译，如此循环。最后还是不能很好理解的情况下就查看中文翻译结果。

**Comment by mozkoe** [comment]
Gorgeous. Convenience to use with a history search panel. ;)

**Comment by noe132** [comment]
添加了一个选项，在设置按钮旁边添加一个历史记录按钮，点击显示最近100条查词记录。默认为不显示

**Comment by noe132** [comment]
已于 `v4.9.0` 发布
