### ISSUE TITLE
希望可以修改小圈圈为别的icon

### ISSUE THREAD

**Issue by cweijan** [Firefox-Pro-Coding/iciba-translate-userscript#41]
首先谢谢老哥, 这个脚本非常牛逼, 现在划词后弹出的小圈圈太丑了, 希望可以内置几个其他好看的icon和支持自定义.

**Comment by cweijan** [comment]
其实倒也不太丑, 主要是这个小圈圈表示的动作和翻译差的有点远, 看起来有点维和
![language](https://user-images.githubusercontent.com/27798227/93693898-515cd480-fb38-11ea-84e9-7cd08bfa6373.png)
![language](https://user-images.githubusercontent.com/27798227/93693907-6f2a3980-fb38-11ea-950f-36a6742a004d.png)
![google](https://user-images.githubusercontent.com/27798227/93693914-92ed7f80-fb38-11ea-8e81-898189bbcad7.png)
![earth](https://user-images.githubusercontent.com/27798227/93693927-c7f9d200-fb38-11ea-91ef-3fb355e82a22.png)
![globe](https://user-images.githubusercontent.com/27798227/93693928-c8926880-fb38-11ea-95ea-d943bcc4e203.png)

**Comment by noe132** [comment]
下个版本会添加几个图标可以自己选择设置小圆圈样式。
有什么好建议也可发来参考一下

**Comment by cweijan** [comment]
上面发了几张, 你看看

**Comment by noe132** [comment]
已于 `v4.9.0` 发布

**Comment by cweijan** [comment]
试了, 非常棒, 谢谢!
