### ISSUE TITLE
划词翻译引擎

### ISSUE THREAD

**Issue by Chensungw** [Firefox-Pro-Coding/iciba-translate-userscript#44]
希望添加划词翻译默认翻译引擎选项！默认的是机器翻译，比如说我想划词后点击小圆圈后就是Google翻译的结果，不用再去多点一下Google的按钮。

**Comment by noe132** [comment]
设置里已经存在默认翻译引擎的选项。在 Core 标签页下。设置从查词输入框右侧的齿轮图标点击进入
