### ISSUE TITLE
谷歌翻译

### ISSUE THREAD

**Issue by noe132** [Firefox-Pro-Coding/iciba-translate-userscript#45]
谷歌翻译 api 更新了，需要重新处理

**Comment by noe132** [comment]
done.

**Comment by omnjpa27516** [comment]
iciba 挂了。
Google 翻译也有问题，选择长句的时候只能翻译第一句。

**Comment by noe132** [comment]
@omnjpa27516 iciba接口更新了，正在处理

**Comment by noe132** [comment]
fix in `v4.9.5`

**Comment by omnjpa27516** [comment]
@noe132 Google翻译又坏掉了

**Comment by noe132** [comment]
@omnjpa27516 出现什么错误？我这刚试了下 google 翻译 没出现问题
![image](https://user-images.githubusercontent.com/2271900/127429969-683a6f13-56d6-47d2-b2b0-8f0c644dc1cc.png)

**Comment by omnjpa27516** [comment]
@noe132 显示
`GOOGLE_TRANSLATE 错误: statuscode`

**Comment by noe132** [comment]
@omnjpa27516 我这暂时无法重现。尝试登陆/退出google账号试试？或者在设置里切换一下google翻译的服务器试试？默认是使用translate.google.com，可以切换到translate.google.cn

**Comment by omnjpa27516** [comment]
@noe132 com和cn都是同样的问题，清除Google的所有网站数据也无法恢复，不过我用金山也可以，谢谢回复

**Comment by noe132** [comment]
@omnjpa27516 正常来说应该不会出现这个问题，我这 chrome92 用匿名模式启用tampermonkey google翻译 没有问题。你试试匿名模式启用扩展？还不行就可能是网络环境问题，不过也不能100%确定

**Comment by omnjpa27516** [comment]
@noe132 那就破案了，这边是Firefox😂
