### ISSUE TITLE
关于删除 prototype.js toJSON 的问题

### ISSUE THREAD

**Issue by feiruo** [Firefox-Pro-Coding/iciba-translate-userscript#46]
https://github.com/Firefox-Pro-Coding/iciba-translate-userscript/blob/3149a4930b601bea821a8d756e77db77ce69438e/src/index.ts#L6

这个删除会导致 Jenkins 项目配置页面出现错误。

表现为控制台可见`render`提交 500 错误，且页面上无法增加输入框。

另外请问下目前删除 prototype.js toJSON 的作用是什么？

**Comment by noe132** [comment]
prototype.js polyfill 的 Array.prototype.toJSON 会让 JSON.stringyfy array 对象时用 这个toJSON方法。但是prototype的实现和默认是不一样的，会导致其他依赖默认实现的代码break。看起来是删掉这个polyfill后让依赖prototype.js的代码break了。

我看看有啥方法可以绕过去

**Comment by noe132** [comment]
`v4.9.8` 把脚本内的 JSON.stringify 调用替换了，会在调用前删除 Array.prototype.toJSON，并在完成后还原回去，这样应该不会出现冲突了。

**Comment by feiruo** [comment]
感谢修复

在 Jenkins 的问题已得到修复。

不过直接在 JSON 上增加  `__stringify`  不知道会不会再次引起其他站点可能出现问题；直接创建  `__stringify`  函数以替换内部 `JSON.stringify` 调用，是否会更好一点？

**Comment by noe132** [comment]
虽然不常见，但是确实会有命名空间冲突的问题。`4.9.9` 改成内部函数调用了。
