### ISSUE TITLE
划词翻译的时候能否默认首字母小写

### ISSUE THREAD

**Issue by MedusaSTears** [Firefox-Pro-Coding/iciba-translate-userscript#48]
有一些单词大写的时候翻译默认成人名模式啥的了,每次都需要自己改成小写开头
本来有一些例子 但是一时半会又想不起来了
希望默认划词翻译的时候,把首字母改成小写翻译,可以增加到设置选项里

**Comment by noe132** [comment]
目前来看只有iciba的接口会有首字母的问题，其他的翻译接口对此似乎影响不大。那就在iciba翻译的选项里加一个首字母自动转换小写的选项，如何？

**Comment by MedusaSTears** [comment]
> 目前来看只有iciba的接口会有首字母的问题，其他的翻译接口对此似乎影响不大。那就在iciba翻译的选项里加一个首字母自动转换小写的选项，如何？

同意!非常感谢!回复的真够快的

**Comment by MedusaSTears** [comment]
> 目前来看只有iciba的接口会有首字母的问题，其他的翻译接口对此似乎影响不大。那就在iciba翻译的选项里加一个首字母自动转换小写的选项，如何？

同意!非常感谢!回复的真够快的

**Comment by noe132** [comment]
已在 `v4.10.0` 添加选项。在 设置 -> ICIBA -> 自动首字母小写。默认是关闭，需要手动打开。
