### ISSUE TITLE
推荐下搜狗翻译

### ISSUE THREAD

**Issue by miaomiaosoft** [Firefox-Pro-Coding/iciba-translate-userscript#5]
**需求描述**
希望可以加上搜狗翻译

**需求说明**
搜狗的英中翻译还是相当不错的，这里有相关讨论 https://www.v2ex.com/t/430327
个人对各家翻译精准度排序 搜狗>腾讯>谷歌>百度

**附加描述**
另外，希望窗口可以自定义宽高 （主要是宽度）
可以增加划词后直接翻译功能
个人强迫症，觉得下面截图中最后的句号可以去除
![QQ截图20190420212352](https://user-images.githubusercontent.com/4084875/56457814-b562f280-63b2-11e9-9343-9265e5c8b6c4.jpg)

谢谢！

**Comment by noe132** [comment]
有时间我会看看搜狗翻译的接口。

末尾的句号和自定义宽高会在下个版本更新。
划词直接翻译我觉可能会带来很多误操作，设置里有个选项，可以hover小圆圈打开查词而不是点击，应该和你想要的功能相似。

**Comment by noe132** [comment]
搜狗翻译在 `v4.1.0` 上线。默认按钮是隐藏状态，需要在设置里勾选显示。
