### ISSUE TITLE
划词翻译在任何界面都无法使用

### ISSUE THREAD

**Issue by hanw233** [Firefox-Pro-Coding/iciba-translate-userscript#50]
现在在**任何**界面划词翻译都无法使用，选中一段文本之后不会跳出小蓝点。
但是在油猴界面中表示划词翻译是正常启用的：
![image](https://user-images.githubusercontent.com/56722028/128158333-c90c971f-be84-4006-9608-8f64400fbe55.png)

使用的浏览器是Microsoft Edge，版本 92.0.902.62 (官方内部版本) (64 位)
划词翻译的版本是4.11.0，是在greasyfork上下载的。

**Comment by noe132** [comment]
v4.11.1 已修复。试一下？

**Comment by hanw233** [comment]
可以正常使用了，感谢作者！
