### ISSUE TITLE
bug~

### ISSUE THREAD

**Issue by chaos-zhu** [Firefox-Pro-Coding/iciba-translate-userscript#51]
![image](https://user-images.githubusercontent.com/44160914/128846657-479e519e-ca29-4144-a48d-f2958e81cc3c.png)

![image](https://user-images.githubusercontent.com/44160914/128846741-329e4721-ea84-44ad-aea6-1540015e6256.png)

**Comment by noe132** [comment]
更新到4.11.1，这个问题在新版本修复了
