### ISSUE TITLE
DevTools警告: DevTools 无法加载来源映射：无法加载

### ISSUE THREAD

**Issue by moreant** [Firefox-Pro-Coding/iciba-translate-userscript#52]
重现步骤
1. 打开 F12
2. DevTools 有如下显示
> DevTools 无法加载来源映射：无法加载 chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/base64-arraybuffer.es5.js.map 的内容：HTTP 错误：状态代码 404，net::ERR_UNKNOWN_URL_SCHEME

页面连接 任何页面
浏览器版本 95.0.4638.69
油猴版本 4.13
脚本版本 4.11.3

**Comment by noe132** [comment]
原因是 webpack 打包时不知为何没有处理掉这个依赖的 sourceMappingURL comment。
v4.11.4 已修复。

**Comment by moreant** [comment]
大佬支持力度拉满啊，插件非常好用，感谢🙏
