### ISSUE TITLE
百度翻译页面划词无弹窗

### ISSUE THREAD

**Issue by 1753135250** [Firefox-Pro-Coding/iciba-translate-userscript#53]
如题所示，打开百度翻译页面，在输入框输入语句，划词后iciba没有图标。
使用场景如下
百度翻译网页版左侧输入段落时，右侧会出现对应的翻译，然而有时我想划词右侧查询具体的个别专业单词的读法和含义，选中以后百度翻译网页版并不能解析全部的单词，有些单词百度翻译不会弹出具体单词的那个选项框，这是就需要配合其他划词插件了，希望大佬能修复百度翻译页面不起作用的bug

**Comment by noe132** [comment]
暂时无法重现。Chrome最新版。
![image](https://user-images.githubusercontent.com/2271900/142440521-5308b7ec-1dd5-4609-9b9f-cb69e26dd7b4.png)
![image](https://user-images.githubusercontent.com/2271900/142440539-6121e844-7eff-48d4-9517-45d007aef282.png)

请带上浏览器版本，截个截图，把出现问题的页面url提供一下。我在 [百度翻译这个页面](https://fanyi.baidu.com/#en/zh/Discover%20the%20innovative%20world%20of%20Apple%20and%20shop%20everything%20iPhone%2C%20iPad%2C%20Apple%20Watch%2C%20Mac%2C%20and%20Apple%20TV%2C%20plus%20explore%20accessories%2C%20entertainment) 并没有重现你描述的问题，如上图，在左边或者右边都能正常显示小圆圈。

**Comment by 1753135250** [comment]
页面就是https://fanyi.baidu.com/，我使用的是暴力猴，chrome版本是96.0.4664.45（正式版本） （64 位），已经关闭所有插件和脚本 ，就是这个网站不弹窗_(:з」∠)_

**Comment by 1753135250** [comment]
![image](https://user-images.githubusercontent.com/52943495/142561058-6fb91077-ffdc-4bfb-af6b-1c319212c08f.png)

**Comment by 1753135250** [comment]
![image](https://user-images.githubusercontent.com/52943495/142561217-2bbb317d-0c8b-4f29-9ee5-b52ff76b3a46.png)
在百度翻译页面可见暴力猴里面无法显示iciba的设置选项

**Comment by noe132** [comment]
v4.11.5 已修复。
百度翻译使用了非标准的 Promise polyfill 导致的错误。Tampermonkey 没出现这个问题，估计是做了一些全局变量的封装隔离。目前在脚本执行前强制把Promise替换成浏览器默认实现。
