### ISSUE TITLE
google play商店网页版脚本无效

### ISSUE THREAD

**Issue by 1753135250** [Firefox-Pro-Coding/iciba-translate-userscript#54]
打开Google play查看安卓应用简介时，发现iciba没有弹出图标

请加上出现问题的环境
 - 页面链接：https://play.google.com/store/apps/details?id=com.zacharee1.systemuituner&hl=en&gl=US
 - 浏览器版本：96.0.4664.110（正式版本） （64 位）
 - 脚本管理扩展：暴力猴v2.13.0

**Comment by noe132** [comment]
`v4.11.6` 已修复。

**Comment by wrxvl8oy** [comment]
> `v4.11.6` 已修复。

@noe132 
这个版本好像不行,任何页面都没反应。
控制台报错：
> ReferenceError: trustedTypes is not defined

降级到`v4.11.5`正常。
Firefox 95.0.2 + Violentmonkey 2.13.0

**Comment by noe132** [comment]
@wrxvl8oy 试试 `v4.11.7`

**Comment by wrxvl8oy** [comment]
好了。半夜修bug辛苦了，感谢！

**Comment by 1753135250** [comment]
> @wrxvl8oy 试试 `v4.11.7`

感谢大佬修bug
