### ISSUE TITLE
F-droid应用详情页面无弹窗

### ISSUE THREAD

**Issue by 1753135250** [Firefox-Pro-Coding/iciba-translate-userscript#55]
我又来反馈bug了

 - 页面链接：https://f-droid.org/packages/nekox.messenger/
 - 浏览器版本：chrome版本 96.0.4664.110（正式版本） （64 位）
 - 脚本管理扩展：暴力猴v2.13.0
-->

**Comment by noe132** [comment]
我这测试是功能是正常的，但是图片无法显示（这是因为页面CSP禁止显示base64 url图片）
![image](https://user-images.githubusercontent.com/2271900/148056835-f3349ed7-cb4d-48a3-ad52-567e8ee7fa51.png)

你看看控制台有没有相关的报错

**Comment by 1753135250** [comment]
确实是这样，点击对应位置可以出现弹窗，但是无图标。这个问题可以修复吗

**Comment by noe132** [comment]
这个不确定能不能修复，也许能通过一些hack的方式解决。我有空试试看

**Comment by 1753135250** [comment]
大佬辛苦了

**Comment by noe132** [comment]
这个图标不显示的问题不是很好解决。具体原因和下面这个 issue 有关。
https://github.com/violentmonkey/violentmonkey/issues/1001
Tampermonkey自带了禁用CSP的功能。用Violentmonkey的话，可以配合 [always-disable-content-se](https://chrome.google.com/webstore/detail/always-disable-content-se/ffelghdomoehpceihalcnbmnodohkibj) 这个扩展使用。
