### ISSUE TITLE
google/baidu里无法正常使用

### ISSUE THREAD

**Issue by yosh3289** [Firefox-Pro-Coding/iciba-translate-userscript#57]
脚本版本：4.11.8
chrome版本：100.0.4896.60
tampermonkey v4.14

在google搜索页/结果页下均能展示小蓝圈，但是点击后无法展示翻译结果
在baidu搜索结果出来以后，对任意元素均无法使用划词翻译。

烦请作者抽空看看

**Comment by noe132** [comment]
我这的测试是 Google 可以正常使用。点击翻译无法展示结果是什么现象？是否有错误信息？控制台是否有相关报错？麻烦截图看看？
![image](https://user-images.githubusercontent.com/2271900/160782984-f3d5c6cb-63fe-4f29-9aab-987e639dec31.png)

百度页面打开时可以使用，但是重新搜索后就无法打开了。这个问题已经确认。稍后会修复

**Comment by noe132** [comment]
`v4.11.9` 已修复 baidu 搜索页的问题。

**Comment by yosh3289** [comment]
> `v4.11.9` 已修复 baidu 搜索页的问题。

感谢修复，已确认问题已解决！

google的问题我在我的mac和windows上测试过了。应该是跟我的代理策略有关。流量通过代理出去的时候，搜索结果页下是能正常使用的，流量未走代理（进入.hk）进入搜索结果页则点击翻译小圆圈无法弹出翻译。
