### ISSUE TITLE
4119无法默认翻译成中文

### ISSUE THREAD

**Issue by lonznt** [Firefox-Pro-Coding/iciba-translate-userscript#58]
脚本是自动更新的，更新之前没有主动修改设置。
更新之后就没办法默认翻译成中文了，只能划词后弹出再用鼠标左键点击相应图标才行。

表现为：
![录制_2022_03_31_01_21_17_443_ 00_00_08-](https://user-images.githubusercontent.com/80406454/160958092-efbe3e21-3819-446b-9a6d-86ef5b4b472e.gif)

这是我的设置，应该没问题吧？
![录制_2022_03_31_01_22_02_425_](https://user-images.githubusercontent.com/80406454/160958110-90679d9e-f095-4a26-bb18-8a0c38ac4c63.gif)

**Comment by noe132** [comment]
你是不是把默认设置成了Vocabulary？在这个设置选项改一下设置默认接口为 百度翻译 即可
![image](https://user-images.githubusercontent.com/2271900/160960093-d7b805c7-e980-40e4-81b1-79a1d1da00b7.png)

**Comment by lonznt** [comment]
是！好了！我的天呢，大佬你为什么要把这个隐藏啊，哈哈哈哈哈哈
