### ISSUE TITLE
ipados safari 调用google翻译时出现“GOOGLE_TRANSLATE 错误: JSON Parse error: Unexpected EOF”提示

### ISSUE THREAD

**Issue by Cullwen** [Firefox-Pro-Coding/iciba-translate-userscript#59]
GOOGLE_TRANSLATE 错误: JSON Parse error: Unexpected EOF

**Comment by noe132** [comment]
不好意思，看了一眼后差点忘记了这个事了~
我手上暂时没有ios/ipados设备，暂时也没法排查问题。你手上有macbook吗，能看看macos上safari也有这个问题吗？如果也有这个问题，我看看可以找朋友借台设备看看，mac可能好弄一点

**Comment by Cullwen** [comment]
感谢回复，mac设备我没有。目前ipados和ios的safari都支持安装插件和脚本的。我的设备是ipad加妙控键盘。经我的测试得出iciba-translate-userscript是ipad端最好用的划词翻译脚本，能兼容设置页面和快捷键，有点无心插柳柳成荫的感觉。虽然ios手机上是完全不能用的，但我主要是在ipad端上使用，我推测ipad和mac的环境应该是一样。如果mac上也出现调用google翻译提示报错此bug，那在mac上修改，应该能同样兼容ipad。

**Comment by noe132** [comment]
好，哪天我有机会有设备了就看一下这个问题

**Comment by noe132** [comment]
bump

**Comment by omnjpa27516** [comment]
借楼反馈一下，这个脚本很好用，点赞~
但是作者能否裁剪一下脚本体积，删除一些不必要的功能和代码~
现在体积已经1.2M了，每个网页都要加载这1M多的脚本，是一笔不小的性能开销~
希望采纳~

**Comment by noe132** [comment]
@omnjpa27516 其实这个脚本最小化压缩后只有300多kb的，可以看最后一个压缩后的版本 [`v4.9.5`](https://github.com/Firefox-Pro-Coding/iciba-translate-userscript/releases/tag/v4.9.5)
之所以不压缩是因为greasyfork[不允许压缩](https://greasyfork.org/zh-CN/help/code-rules#:~:text=%E6%8F%90%E4%BA%A4%E5%88%B0%20Greasy%20Fork%20%E7%9A%84%E4%BB%A3%E7%A0%81%E4%B8%8D%E5%BE%97%E6%B7%B7%E6%B7%86%E6%88%96%E6%9C%80%E5%B0%8F%E5%8C%96)。

代码本身已经做到十分紧凑了，除了一些基础第三方库和 polyfill，基本不包含其他第三方组件库。代码可以说几乎没有多余的东西。

因为几乎所有的用户都是从 greasyfork 安装，所以不太可能上传压缩后的版本到 greasyfork。如果你懂一些相关的知识可以自己编译一个压缩后的版本，大概流程是 安装 node, 用 npm 安装 yarn，把代码 clone 下来，运行 yarn install 安装依赖，然后 注释[这个文件](https://github.com/Firefox-Pro-Coding/iciba-translate-userscript/blob/a93b6bb61ead456574c946a46f86eff213b66fee/build/config/webpack/webpack.prod.conf.js#L13)第13行，再取消掉14-22行的注释，运行 `yarn build` 就会在 `dist` 文件夹打包生成压缩后的文件。我这里把目前最新版本 4.11.9 打包了一个压缩后的版本 [iciba.user.zip](https://github.com/Firefox-Pro-Coding/iciba-translate-userscript/files/8857886/iciba.user.zip)，这个打包出来是 334kb 的大小，功能和 1M 多的是完全一致的，可以下载解压后拖到浏览器里安装。缺点是不像从 greasyfork 安装的能自动更新。

![image](https://user-images.githubusercontent.com/2271900/172518296-6257fc5b-f20c-4aec-892a-edcdb815c1ce.png)

**Comment by omnjpa27516** [comment]
@noe132 感谢解答，了解了~

**Comment by uccamnj** [comment]
@noe132 脚本很棒👍 发现个小问题，如果 Firefox 开启 HTTPS-Only-Mode ，Violentmonkey 更新时，脚本的 [icon](http://tb.himg.baidu.com/sys/portrait/item/d4346e6f65313332ac06) 因为未使用 HTTPS 加载失败。如果可能的话，希望能换个图床，谢谢。

![img](https://user-images.githubusercontent.com/107554397/173826949-62335bb4-c597-42ca-869b-9a5474514daf.png)

**Comment by noe132** [comment]
@uccamnj 明白。下次更新会改一下

**Comment by omnjpa27516** [comment]
@noe132 作者可以考虑升级一下vue3+vite，体积能减小不少，至少corejs不再需要了~

**Comment by Cullwen** [comment]
脚本很好用，但感觉差一个带热键的全网页翻译的功能，作者是否考虑添加此功能？

**Comment by noe132** [comment]
@Cullwen 这种功能chrome自带的翻译就足够了，而且也有很多第三方扩展有这样的功能。这个脚本主要提供的是划词翻译查词。
