### ISSUE TITLE
打开设置布局重叠

### ISSUE THREAD

**Issue by hosxy** [Firefox-Pro-Coding/iciba-translate-userscript#6]
**问题描述**
打开设置布局重叠

**重现**
打开设置

**截图**
![批注 2019-04-21 212421](https://user-images.githubusercontent.com/17108640/56470762-92047a00-647c-11e9-8890-fb8d28bb8eca.png)

**环境**
 - 用户脚本版本: 4.0.8
 - 系统: Windows 10
 - 浏览器及版本 : firefox 66.03
 - 脚本管理扩展 : violentmonkey

**Comment by noe132** [comment]
这个问题解决不了。原因是页面的 CSP 阻止加载 base64 编码的字体，而图标是iconfont使用到了所需要的字体
目前只有设置页面使用到了 iconfont，查词框的图标都是svg，所以没有影响。
解决方案：换一个页面设置

**Comment by noe132** [comment]
之后可能会考虑去掉 iconfont 仅使用 svg，不过暂时不会修改，因为要重新写所用到的组件
