### ISSUE TITLE
调用百度翻译提示：BAIDU_TRANSLATE 错误: failed to get gtk

### ISSUE THREAD

**Issue by Lotusice** [Firefox-Pro-Coding/iciba-translate-userscript#60]
请简要并详细的描述你所遇到的问题。
调用百度翻译提示：BAIDU_TRANSLATE 错误: failed to get gtk

请加上出现问题的环境
 - 页面链接：任何网页复现
 - 浏览器版本： Vivaldi 5.3.2679.68 (Stable channel) （64 位） 
 - 系统：Windows 10 21H2
  - 脚本管理扩展：Tampermonkey [v4.16.1]

**Comment by noe132** [comment]
`v4.11.10` 已修复

**Comment by c8kh2necaamm** [comment]
> 

感谢
