### ISSUE TITLE
谷歌翻译出现异常

### ISSUE THREAD

**Issue by 1753135250** [Firefox-Pro-Coding/iciba-translate-userscript#66]
不挂代理的时候，谷歌翻译会显示‘GOOGLE_TRANSLATE 错误: Cannot read properties of undefined (reading 'substring')’
挂了代理就正常，我已经更改了系统hosts‘translate.googleapis.com’，浏览器的网页翻译是可以用的，请问下iciba用的是哪个接口呀，也需要更改hosts吗

**Comment by noe132** [comment]
用的是 translate.google.com。

**Comment by 1753135250** [comment]
> 用的是 translate.google.com。

请问下现在国内不挂代理，还有什么方法可以使用脚本里面的谷歌翻译服务吗

**Comment by noe132** [comment]
> 请问下现在国内不挂代理，还有什么方法可以使用脚本里面的谷歌翻译服务吗

这个我就不太清楚了。。之前是看到有改 host 的方法，不过我也没有尝试过。自从 translate.google.cn 不能用后，挂代理是比较稳定的做法。
