### ISSUE TITLE
twitter\github等网站无法使用插件

### ISSUE THREAD

**Issue by phoenixlaw85** [Firefox-Pro-Coding/iciba-translate-userscript#68]

**Comment by noe132** [comment]
未能重现。请检查是不是和其他扩展/脚本有冲突
![image](https://user-images.githubusercontent.com/2271900/203242010-8df42cd8-aed7-4d50-b221-269a6f9dffc8.png)
![image](https://user-images.githubusercontent.com/2271900/203242045-b91241d9-4b52-45b5-ab01-2368359c2c48.png)

**Comment by phoenixlaw85** [comment]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/34760439/203242604-a53816db-da67-4a98-ad4c-e15d99a2f7b3.png">
<img width="315" alt="image" src="https://user-images.githubusercontent.com/34760439/203242660-95bdf0fe-3df8-4189-9325-74b9216bf35c.png">
两个网站的插件一致
