### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by miaomiaosoft** [Firefox-Pro-Coding/iciba-translate-userscript#7]
**问题描述**
1. 在特定网站翻译窗口内按钮错位/不可见
2. 搜狗翻译应该支持来源语言为AUTO，翻译中文会返回英文，目前翻译中文会提示错误

**重现步骤**
1. 重现网址[FBI警告]：https://www.pornhub.com/view_video.php?viewkey=ph5c14d20371749

**截图**
1.
![QQ截图20190427094313](https://user-images.githubusercontent.com/4084875/56843270-0736db80-68d1-11e9-9845-c2a59dd3f2da.jpg)

**环境**
 - 用户脚本版本: [e.g. 4.1.0]
 - 系统: [e.g. Windows 7]
 - 浏览器及版本 [e.g. chrome 72]
 - 脚本管理扩展 [e.g. tampermonkey]

**Comment by noe132** [comment]
fixed in `v4.1.1`.
