### ISSUE TITLE
为啥对firefox版本要求这么高？

### ISSUE THREAD

**Issue by hosxy** [Firefox-Pro-Coding/iciba-translate-userscript#8]
**需求描述**
能否将需要的 firefox 版本降低，比如 52.9ESR

**需求说明**
老版本火狐无法使用

**Comment by noe132** [comment]
因为用到了 [`shadow dom`](https://www.caniuse.com/#search=shadowdom) 做样式隔离，而 shador dom 是从 firefox 59 开始默认启用的。https://www.caniuse.com/#search=shadowdom

**Comment by noe132** [comment]
firefox 29 支持 shadow dom v0，理论上也是支持的，不过没有测试，不能保证低版本一定能用。
我这里简单测试了一下 firefox 57，开启 `dom.webcomponents.enabled` 后没有目前没有发现大问题。

等下我更新 `v4.1.2` 加上 shadow dom v0 的支持。

**Comment by noe132** [comment]
已更新 `v4.1.2`。
