### ISSUE TITLE
老版本火狐，设置页面打不开

### ISSUE THREAD

**Issue by hosxy** [Firefox-Pro-Coding/iciba-translate-userscript#9]
**问题描述**
老版本火狐打开 dom.webcomponents.enabled 后可以使用了，但是设置页面打不开

**重现步骤**
划词翻译页面，点设置没有反应

**环境**
 - 用户脚本版本: 4.1.2
 - 系统: Windows 10
 - 浏览器及版本:  firefox 52.9 ESR/Basilisk 20190327 
 - 脚本管理扩展:  greasemonkey

**Comment by noe132** [comment]
最低测试到 firefox 38.8 esr，没有问题。
Basilisk 会出现按钮上的图标遮盖了按钮的点击事件的bug，导致点不到。解决方案：点按钮边上非图标的白色区域。
设置窗口内的部分也一样，会出现选项点不动，得点边上的白色区域。

建议使用Firefox原版而非第三方修改版。

**Comment by noe132** [comment]
ps: 很可能是因为Basilisk `shadow dom` 内事件不知为何不能冒泡，添加在父元素上的事件监听，点在子元素上监听不到，于是事件监听器接收不到点击事件。
这个问题应该暂时无解。😕

原版firefox无此问题，建议使用原版。
